name: Build and publish libplctag.NET nuget package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore  './src/libplctag/libplctag.csproj'
    - name: Pack
      run: dotnet pack './src/libplctag/libplctag.csproj' --configuration Release
    - name: Publish
      run: dotnet nuget push './src/libplctag/bin/Release/libplctag.*.nupkg' -k ${{secrets.NUGET_API_KEY}} --source "github"
