name: Build and publish libplctag.NET nuget package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true 
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
        
    - name: Install dependencies
      run: dotnet restore './src/'
      
    - name: Build
      run: dotnet build --configuration Release --no-restore './src/'
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: './src/libplctag/bin/Release/libplctag.*.nupkg'
        
    - name: Build package in known location
      run: dotnet pack --configuration Release -o out './src/libplctag/libplctag.csproj'
    
    - name: ls
      run: ls -r
      
    - name: Publish
      run: dotnet nuget push './out/*.nupkg' --no-symbols true
